# Netlify 프로젝트의 빌드 및 개발 설정 파일입니다.

[build]
  # Netlify에 배포할 때 사용되는 빌드 명령어입니다.
  command = "npm run build"
  # 빌드된 파일이 Netlify에 배포될 폴더입니다. Vite의 기본 출력 폴더는 'dist'입니다.
  publish = "dist"
  # 서버리스 함수들이 위치한 폴더를 명시합니다.
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  # 빌드 시에는 Vite 환경 변수만 필요 (클라이언트 사이드)
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""

[dev]
  # 'netlify dev' 명령어를 실행할 때 사용되는 로컬 개발 서버 명령어입니다.
  command = "npm run dev"
  # Netlify Dev가 Vite 서버(5173)를 바라보도록 이 포트를 명시해야 합니다.
  targetPort = 5173
  # 로컬 개발 시 빌드 출력 폴더를 지정합니다
  publish = "dist"
  # Vite 프레임워크 명시적 설정 - SPA 모드 비활성화
  framework = "#custom"
  # Netlify Functions 폴더
  functions = "netlify/functions"
  # Netlify CLI의 주 서버 포트 
  port = 8888
  # Functions 자동 리로드 활성화
  functionsSource = "netlify/functions"
  # 파일 변경 감지 활성화
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # 함수 디렉토리 명시
  directory = "netlify/functions"
  # 모든 함수에 대해 esbuild 번들러를 사용하도록 지정합니다.
  node_bundler = "esbuild"

# 기본 함수 설정
[functions."*"]
  timeout = 60000
  format = "esm"

# 주요 함수들에 대해 환경 변수 명시적 지정 (4KB 제한 준수)
[functions.storyboardGenerator]
  environment = { SUPABASE_URL = "", SUPABASE_SERVICE_ROLE_KEY = "", VITE_SUPABASE_URL = "", FAL_API_KEY = "" }

[functions.generateVideoAsync]
  environment = { SUPABASE_URL = "", SUPABASE_SERVICE_ROLE_KEY = "", VITE_SUPABASE_URL = "", FAL_API_KEY = "", GENERATIVE_LANGUAGE_API_KEY = "" }

[functions.generateGptImage]
  environment = { SUPABASE_URL = "", SUPABASE_SERVICE_ROLE_KEY = "", VITE_SUPABASE_URL = "", OPENAI_API_KEY = "" }

[functions.generateFluxImage]
  environment = { SUPABASE_URL = "", SUPABASE_SERVICE_ROLE_KEY = "", VITE_SUPABASE_URL = "", FAL_API_KEY = "" }

[functions.check-job-status]
  environment = { FAL_API_KEY = "" }

[functions.checkApiKeys]
  environment = { SUPABASE_URL = "", SUPABASE_SERVICE_ROLE_KEY = "" }

# 원고 분석 함수들
[functions.analyze-script-quick]
  environment = { SUPABASE_URL = "", SUPABASE_SERVICE_ROLE_KEY = "", VITE_SUPABASE_URL = "", GENERATIVE_LANGUAGE_API_KEY = "" }

[functions.analyze-script-async]
  environment = { SUPABASE_URL = "", SUPABASE_SERVICE_ROLE_KEY = "", VITE_SUPABASE_URL = "", GENERATIVE_LANGUAGE_API_KEY = "" }

[functions.analyze-script]
  environment = { SUPABASE_URL = "", SUPABASE_SERVICE_ROLE_KEY = "", VITE_SUPABASE_URL = "", GENERATIVE_LANGUAGE_API_KEY = "" }

# 구글 드라이브 백업 기능은 제거됨 (Supabase Storage 사용)