# Netlify 프로젝트의 빌드 및 개발 설정 파일입니다.

[build]
  # Netlify에 배포할 때 사용되는 빌드 명령어입니다.
  command = "npm run build"
  # 빌드된 파일이 Netlify에 배포될 폴더입니다. Vite의 기본 출력 폴더는 'dist'입니다.
  publish = "dist"
  # 서버리스 함수들이 위치한 폴더를 명시합니다.
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[dev]
  # 'netlify dev' 명령어를 실행할 때 사용되는 로컬 개발 서버 명령어입니다.
  command = "npm run dev"
  # Netlify Dev가 Vite 서버(5173)를 바라보도록 이 포트를 명시해야 합니다.
  targetPort = 5173
  # 로컬 개발 시 빌드 출력 폴더를 지정합니다
  publish = "dist"
  # Vite 프레임워크 명시적 설정 - SPA 모드 비활성화
  framework = "#custom"
  # Netlify Functions 폴더
  functions = "netlify/functions"
  # Netlify CLI의 주 서버 포트 
  port = 8888
  # Functions 자동 리로드 활성화
  functionsSource = "netlify/functions"
  # 파일 변경 감지 활성화
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # 함수 디렉토리 명시
  directory = "netlify/functions"
  # 모든 함수에 대해 esbuild 번들러를 사용하도록 지정합니다.
  node_bundler = "esbuild"

[functions."*"]
  # 타임아웃을 60초로 설정합니다 (최대 60초까지 가능)
  timeout = 60000
  # ES Module 형식 사용 (import/export 지원)
  format = "esm"

# 핵심 함수들에만 필요한 환경 변수 설정
[functions."analyze-script-quick"]
[functions."analyze-script-quick".environment]
  GOOGLE_API_KEY = ""
  SUPABASE_URL = ""
  SUPABASE_ANON_KEY = ""

[functions."analyze-script-async"]
[functions."analyze-script-async".environment]
  GOOGLE_API_KEY = ""
  SUPABASE_URL = ""
  SUPABASE_ANON_KEY = ""

[functions."generatePhotoAvatar"]
[functions."generatePhotoAvatar".environment]
  HEYGEN_API_KEY = ""
  SUPABASE_URL = ""
  SUPABASE_ANON_KEY = ""

[functions."generateHeyGenAvatar"]
[functions."generateHeyGenAvatar".environment]
  HEYGEN_API_KEY = ""
  SUPABASE_URL = ""
  SUPABASE_ANON_KEY = ""

[functions."getHeyGenAvatars"]
[functions."getHeyGenAvatars".environment]
  HEYGEN_API_KEY = ""

[functions."getHeyGenVoices"]
[functions."getHeyGenVoices".environment]
  HEYGEN_API_KEY = ""

[functions."checkHeyGenStatus"]
[functions."checkHeyGenStatus".environment]
  HEYGEN_API_KEY = ""
  SUPABASE_URL = ""
  SUPABASE_ANON_KEY = ""

[functions."checkHeyGenVideoStatus"]
[functions."checkHeyGenVideoStatus".environment]
  HEYGEN_API_KEY = ""
  SUPABASE_URL = ""
  SUPABASE_ANON_KEY = ""

[functions."generateVeo3PreviewVideo"]
[functions."generateVeo3PreviewVideo".environment]
  GOOGLE_API_KEY = ""
  SUPABASE_URL = ""
  SUPABASE_ANON_KEY = ""

[functions."generateVeo3FastVideo"]
[functions."generateVeo3FastVideo".environment]
  GOOGLE_API_KEY = ""
  SUPABASE_URL = ""
  SUPABASE_ANON_KEY = ""